spring:
  profiles:
    active: "${SPRING_PROFILES_ACTIVE:local}"
--- #LOCAL
spring:
  config:
    activate:
      on-profile: local
  application:
    name: library-events-producer
  kafka:
    topic:  "library-events"
    producer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        retries: 5
        retry.backoff.ms: 1000
    admin:
      properties:
        bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
---
server:
  port: 8080

logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){blue} %highlight(%5p) %clr([%15.15t]){green} %clr(%-40.40logger{39}){cyan} %clr(:){red} %m%n%throwable"